# -*- coding: utf-8 -*-
"""TodoListPy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g8-OsYEL1lCv38F3DPctx-H51dQ3vFMb
"""

# Define the structure of a task as a dictionary
# 'tasks' is a list to store multiple tasks
tasks = []

# Function to add a task to the list
def add_task(task):
    task_item = {
        "task": task,
        "completed": False
    }
    tasks.append(task_item)
    print(f"Task '{task}' added successfully.")

# Function to delete a task from the list by its index
def delete_task(index):
    if 0 <= index < len(tasks):
        removed_task = tasks.pop(index)
        print(f"Task '{removed_task['task']}' deleted successfully.")
    else:
        print("Invalid index. Please try again.")

# Function to display all tasks in the list
def display_tasks():
    if not tasks:
        print("No tasks to display.")
    else:
        print("To-Do List:")
        for i, task in enumerate(tasks):
            status = "✔️" if task['completed'] else "❌"
            print(f"{i + 1}. {task['task']} - {status}")

# Function to mark a task as complete by its index
def mark_task_complete(index):
    if 0 <= index < len(tasks):
        tasks[index]['completed'] = True
        print(f"Task '{tasks[index]['task']}' marked as complete.")
    else:
        print("Invalid index. Please try again.")

# Main loop to interact with the user
def main():
    while True:
        print("\nOptions:")
        print("1. Add a Task")
        print("2. Delete a Task")
        print("3. Display Tasks")
        print("4. Mark Task as Complete")
        print("5. Exit")

        choice = input("Enter your choice (1-5): ")

        if choice == '1':
            task = input("Enter the task: ")
            add_task(task)
        elif choice == '2':
            display_tasks()
            index = int(input("Enter the task number to delete: ")) - 1
            delete_task(index)
        elif choice == '3':
            display_tasks()
        elif choice == '4':
            display_tasks()
            index = int(input("Enter the task number to mark as complete: ")) - 1
            mark_task_complete(index)
        elif choice == '5':
            print("Exiting the To-Do List App. Goodbye!")
            break
        else:
            print("Invalid choice. Please try again.")

# Run the main loop
if __name__ == "__main__":
    main()